#Kindle Publisher Configuration
#Tue Mar 03 20:32:40 CST 2026
auth.code=UKpa3CfCZwPa4DNE
homework.title=2026-02-28 21\:25\:44\u4F5C\u4E1A
kindle.email=18600153020@kindle.com
sender.email=qazxcvbnm.2000@163.com
